@isTest
public class AggregateOrderExtensionTest {
    private AggregateOrderExtension extension;
    private ApexPages.StandardController controller;
    
    testMethod static void testSave_returns_the_correct_page() {
    }

    testMethod static void testSave_when_creating_creates_a_new_aggregate_order() {
    }

    testMethod static void testSave_when_creating_creates_aggregate_order_details() {
    }

    testMethod static void testSave_when_amending_updates_the_aggregate_order() {
    }

    testMethod static void testSave_when_amending_updates_the_aggregate_order_details() {
    }
}